# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_chatgroup.proto',
  package='',
  serialized_pb='\n\x13msg_chatgroup.proto\x1a\x13res_chatgroup.proto\x1a\x0eres_user.proto\x1a\x0fres_arena.proto\"m\n\x0f\x43hatGroupJoined\x12\x13\n\x0b\x63hatGroupID\x18\x01 \x01(\r\x12\"\n\tchatGroup\x18\x02 \x01(\x0b\x32\x0f.ChatGroupModel\x12!\n\x06\x61renas\x18\x03 \x03(\x0b\x32\x11.ArenaInChatGroup\"&\n\x0f\x43hatGroupLeaved\x12\x13\n\x0b\x63hatGroupID\x18\x01 \x01(\r\"T\n\x13UserJoinedChatGroup\x12\x13\n\x0b\x63hatGroupID\x18\x01 \x01(\r\x12\x0e\n\x06userID\x18\x02 \x01(\r\x12\x18\n\x04user\x18\x03 \x01(\x0b\x32\n.UserModel\":\n\x13UserLeavedChatGroup\x12\x13\n\x0b\x63hatGroupID\x18\x01 \x01(\r\x12\x0e\n\x06userID\x18\x02 \x01(\r\"G\n\x16\x43hatGroupMemberUpdated\x12\x13\n\x0b\x63hatGroupID\x18\x01 \x01(\r\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.UserModel\"{\n\x10\x41renaInChatGroup\x12\x13\n\x0b\x63hatGroupID\x18\x01 \x01(\r\x12\x11\n\tcreatorID\x18\x02 \x01(\r\x12\x0f\n\x07\x61renaID\x18\x03 \x01(\r\x12\x13\n\x0b\x63reatorName\x18\x04 \x01(\t\x12\x19\n\x05\x61rena\x18\x05 \x01(\x0b\x32\n.ArenaMiniB\r\n\tproto.msgH\x02')




_CHATGROUPJOINED = descriptor.Descriptor(
  name='ChatGroupJoined',
  full_name='ChatGroupJoined',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='chatGroupID', full_name='ChatGroupJoined.chatGroupID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chatGroup', full_name='ChatGroupJoined.chatGroup', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='arenas', full_name='ChatGroupJoined.arenas', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=77,
  serialized_end=186,
)


_CHATGROUPLEAVED = descriptor.Descriptor(
  name='ChatGroupLeaved',
  full_name='ChatGroupLeaved',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='chatGroupID', full_name='ChatGroupLeaved.chatGroupID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=188,
  serialized_end=226,
)


_USERJOINEDCHATGROUP = descriptor.Descriptor(
  name='UserJoinedChatGroup',
  full_name='UserJoinedChatGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='chatGroupID', full_name='UserJoinedChatGroup.chatGroupID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userID', full_name='UserJoinedChatGroup.userID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='UserJoinedChatGroup.user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=228,
  serialized_end=312,
)


_USERLEAVEDCHATGROUP = descriptor.Descriptor(
  name='UserLeavedChatGroup',
  full_name='UserLeavedChatGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='chatGroupID', full_name='UserLeavedChatGroup.chatGroupID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userID', full_name='UserLeavedChatGroup.userID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=314,
  serialized_end=372,
)


_CHATGROUPMEMBERUPDATED = descriptor.Descriptor(
  name='ChatGroupMemberUpdated',
  full_name='ChatGroupMemberUpdated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='chatGroupID', full_name='ChatGroupMemberUpdated.chatGroupID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='ChatGroupMemberUpdated.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=374,
  serialized_end=445,
)


_ARENAINCHATGROUP = descriptor.Descriptor(
  name='ArenaInChatGroup',
  full_name='ArenaInChatGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='chatGroupID', full_name='ArenaInChatGroup.chatGroupID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='creatorID', full_name='ArenaInChatGroup.creatorID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='arenaID', full_name='ArenaInChatGroup.arenaID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='creatorName', full_name='ArenaInChatGroup.creatorName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='arena', full_name='ArenaInChatGroup.arena', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=447,
  serialized_end=570,
)

import res_chatgroup_pb2
import res_user_pb2
import res_arena_pb2

_CHATGROUPJOINED.fields_by_name['chatGroup'].message_type = res_chatgroup_pb2._CHATGROUPMODEL
_CHATGROUPJOINED.fields_by_name['arenas'].message_type = _ARENAINCHATGROUP
_USERJOINEDCHATGROUP.fields_by_name['user'].message_type = res_user_pb2._USERMODEL
_CHATGROUPMEMBERUPDATED.fields_by_name['user'].message_type = res_user_pb2._USERMODEL
_ARENAINCHATGROUP.fields_by_name['arena'].message_type = res_arena_pb2._ARENAMINI

class ChatGroupJoined(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHATGROUPJOINED
  
  # @@protoc_insertion_point(class_scope:ChatGroupJoined)

class ChatGroupLeaved(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHATGROUPLEAVED
  
  # @@protoc_insertion_point(class_scope:ChatGroupLeaved)

class UserJoinedChatGroup(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERJOINEDCHATGROUP
  
  # @@protoc_insertion_point(class_scope:UserJoinedChatGroup)

class UserLeavedChatGroup(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLEAVEDCHATGROUP
  
  # @@protoc_insertion_point(class_scope:UserLeavedChatGroup)

class ChatGroupMemberUpdated(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHATGROUPMEMBERUPDATED
  
  # @@protoc_insertion_point(class_scope:ChatGroupMemberUpdated)

class ArenaInChatGroup(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARENAINCHATGROUP
  
  # @@protoc_insertion_point(class_scope:ArenaInChatGroup)

# @@protoc_insertion_point(module_scope)
