# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_chat.proto',
  package='',
  serialized_pb='\n\x0emsg_chat.proto\"S\n\tGroupChat\x12\x0f\n\x07groupID\x18\x01 \x01(\r\x12\x10\n\x08senderID\x18\x02 \x01(\r\x12\x12\n\nreceiverID\x18\x03 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\tB\r\n\tproto.msgH\x02')




_GROUPCHAT = descriptor.Descriptor(
  name='GroupChat',
  full_name='GroupChat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='groupID', full_name='GroupChat.groupID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='senderID', full_name='GroupChat.senderID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='receiverID', full_name='GroupChat.receiverID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='GroupChat.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=101,
)



class GroupChat(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GROUPCHAT
  
  # @@protoc_insertion_point(class_scope:GroupChat)

# @@protoc_insertion_point(module_scope)
