# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_campus_arena.proto',
  package='',
  serialized_pb='\n\x16msg_campus_arena.proto\x1a\x16res_campus_arena.proto\"-\n\x07\x43\x61Queue\x12\"\n\x04item\x18\x01 \x02(\x0b\x32\x14.CampusArenaGroupingB\r\n\tproto.msgH\x02')




_CAQUEUE = descriptor.Descriptor(
  name='CaQueue',
  full_name='CaQueue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='item', full_name='CaQueue.item', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=95,
)

import res_campus_arena_pb2

_CAQUEUE.fields_by_name['item'].message_type = res_campus_arena_pb2._CAMPUSARENAGROUPING

class CaQueue(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAQUEUE
  
  # @@protoc_insertion_point(class_scope:CaQueue)

# @@protoc_insertion_point(module_scope)
