# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_team.proto',
  package='',
  serialized_pb='\n\x0emsg_team.proto\x1a\x0eres_team.proto\"<\n\nTeamJoined\x12\x0e\n\x06teamID\x18\x01 \x01(\r\x12\x1e\n\x04team\x18\x02 \x01(\x0b\x32\x10.TeamGetResponse\",\n\nTeamLeaved\x12\x1e\n\x04team\x18\x01 \x02(\x0b\x32\x10.TeamGetResponse\"l\n\x0eUserJoinedTeam\x12\x0e\n\x06teamID\x18\x01 \x01(\r\x12\x0e\n\x06userID\x18\x02 \x01(\r\x12\x10\n\x08userName\x18\x03 \x01(\t\x12\x14\n\x0cuserPortrait\x18\x04 \x01(\t\x12\x12\n\nuserStatus\x18\x05 \x01(\t\"0\n\x0eUserLeavedTeam\x12\x0e\n\x06teamID\x18\x01 \x01(\r\x12\x0e\n\x06userID\x18\x02 \x01(\r\"\x8a\x01\n\x0eTeamInvitation\x12\x12\n\noperatorID\x18\x01 \x01(\r\x12\x14\n\x0coperatorName\x18\x02 \x01(\t\x12\x18\n\x10operatorPortrait\x18\x03 \x01(\t\x12\x1e\n\x04team\x18\x04 \x01(\x0b\x32\x10.TeamGetResponse\x12\x14\n\x0ctargetUserID\x18\x05 \x01(\r\"\x9b\x01\n\x1dTeamJoiningApplicationMessage\x12\x0e\n\x06userID\x18\x02 \x01(\r\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x10\n\x08userName\x18\x04 \x01(\t\x12\x14\n\x0cuserPortrait\x18\x05 \x01(\t\x12\x1e\n\x04team\x18\x01 \x01(\x0b\x32\x10.TeamGetResponse\x12\x12\n\nca05_order\x18\x06 \x01(\r\"t\n\x17TeamMemberStatusUpdated\x12\x0e\n\x06teamID\x18\x01 \x01(\r\x12\x0e\n\x06userID\x18\x02 \x01(\r\x12\x12\n\nuserStatus\x18\x03 \x01(\t\x12\x13\n\x0bisAssistant\x18\x04 \x01(\x08\x12\x10\n\x08isLeader\x18\x05 \x01(\x08\"@\n\x1eTeamJoiningApplicationAccepted\x12\x1e\n\x04team\x18\x01 \x01(\x0b\x32\x10.TeamGetResponse\"@\n\x1eTeamJoiningApplicationDeclined\x12\x1e\n\x04team\x18\x01 \x01(\x0b\x32\x10.TeamGetResponse\"/\n\rTeamDisbanded\x12\x1e\n\x04team\x18\x01 \x02(\x0b\x32\x10.TeamGetResponse\"3\n\x11TeamLeaderChanged\x12\x1e\n\x04team\x18\x01 \x02(\x0b\x32\x10.TeamGetResponseB\r\n\tproto.msgH\x02')




_TEAMJOINED = descriptor.Descriptor(
  name='TeamJoined',
  full_name='TeamJoined',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='teamID', full_name='TeamJoined.teamID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='team', full_name='TeamJoined.team', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=94,
)


_TEAMLEAVED = descriptor.Descriptor(
  name='TeamLeaved',
  full_name='TeamLeaved',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='team', full_name='TeamLeaved.team', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=96,
  serialized_end=140,
)


_USERJOINEDTEAM = descriptor.Descriptor(
  name='UserJoinedTeam',
  full_name='UserJoinedTeam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='teamID', full_name='UserJoinedTeam.teamID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userID', full_name='UserJoinedTeam.userID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userName', full_name='UserJoinedTeam.userName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userPortrait', full_name='UserJoinedTeam.userPortrait', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userStatus', full_name='UserJoinedTeam.userStatus', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=142,
  serialized_end=250,
)


_USERLEAVEDTEAM = descriptor.Descriptor(
  name='UserLeavedTeam',
  full_name='UserLeavedTeam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='teamID', full_name='UserLeavedTeam.teamID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userID', full_name='UserLeavedTeam.userID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=252,
  serialized_end=300,
)


_TEAMINVITATION = descriptor.Descriptor(
  name='TeamInvitation',
  full_name='TeamInvitation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='operatorID', full_name='TeamInvitation.operatorID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operatorName', full_name='TeamInvitation.operatorName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operatorPortrait', full_name='TeamInvitation.operatorPortrait', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='team', full_name='TeamInvitation.team', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='targetUserID', full_name='TeamInvitation.targetUserID', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=303,
  serialized_end=441,
)


_TEAMJOININGAPPLICATIONMESSAGE = descriptor.Descriptor(
  name='TeamJoiningApplicationMessage',
  full_name='TeamJoiningApplicationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userID', full_name='TeamJoiningApplicationMessage.userID', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='TeamJoiningApplicationMessage.reason', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userName', full_name='TeamJoiningApplicationMessage.userName', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userPortrait', full_name='TeamJoiningApplicationMessage.userPortrait', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='team', full_name='TeamJoiningApplicationMessage.team', index=4,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ca05_order', full_name='TeamJoiningApplicationMessage.ca05_order', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=444,
  serialized_end=599,
)


_TEAMMEMBERSTATUSUPDATED = descriptor.Descriptor(
  name='TeamMemberStatusUpdated',
  full_name='TeamMemberStatusUpdated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='teamID', full_name='TeamMemberStatusUpdated.teamID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userID', full_name='TeamMemberStatusUpdated.userID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userStatus', full_name='TeamMemberStatusUpdated.userStatus', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isAssistant', full_name='TeamMemberStatusUpdated.isAssistant', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isLeader', full_name='TeamMemberStatusUpdated.isLeader', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=601,
  serialized_end=717,
)


_TEAMJOININGAPPLICATIONACCEPTED = descriptor.Descriptor(
  name='TeamJoiningApplicationAccepted',
  full_name='TeamJoiningApplicationAccepted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='team', full_name='TeamJoiningApplicationAccepted.team', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=719,
  serialized_end=783,
)


_TEAMJOININGAPPLICATIONDECLINED = descriptor.Descriptor(
  name='TeamJoiningApplicationDeclined',
  full_name='TeamJoiningApplicationDeclined',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='team', full_name='TeamJoiningApplicationDeclined.team', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=785,
  serialized_end=849,
)


_TEAMDISBANDED = descriptor.Descriptor(
  name='TeamDisbanded',
  full_name='TeamDisbanded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='team', full_name='TeamDisbanded.team', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=851,
  serialized_end=898,
)


_TEAMLEADERCHANGED = descriptor.Descriptor(
  name='TeamLeaderChanged',
  full_name='TeamLeaderChanged',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='team', full_name='TeamLeaderChanged.team', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=900,
  serialized_end=951,
)

import res_team_pb2

_TEAMJOINED.fields_by_name['team'].message_type = res_team_pb2._TEAMGETRESPONSE
_TEAMLEAVED.fields_by_name['team'].message_type = res_team_pb2._TEAMGETRESPONSE
_TEAMINVITATION.fields_by_name['team'].message_type = res_team_pb2._TEAMGETRESPONSE
_TEAMJOININGAPPLICATIONMESSAGE.fields_by_name['team'].message_type = res_team_pb2._TEAMGETRESPONSE
_TEAMJOININGAPPLICATIONACCEPTED.fields_by_name['team'].message_type = res_team_pb2._TEAMGETRESPONSE
_TEAMJOININGAPPLICATIONDECLINED.fields_by_name['team'].message_type = res_team_pb2._TEAMGETRESPONSE
_TEAMDISBANDED.fields_by_name['team'].message_type = res_team_pb2._TEAMGETRESPONSE
_TEAMLEADERCHANGED.fields_by_name['team'].message_type = res_team_pb2._TEAMGETRESPONSE

class TeamJoined(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMJOINED
  
  # @@protoc_insertion_point(class_scope:TeamJoined)

class TeamLeaved(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMLEAVED
  
  # @@protoc_insertion_point(class_scope:TeamLeaved)

class UserJoinedTeam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERJOINEDTEAM
  
  # @@protoc_insertion_point(class_scope:UserJoinedTeam)

class UserLeavedTeam(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLEAVEDTEAM
  
  # @@protoc_insertion_point(class_scope:UserLeavedTeam)

class TeamInvitation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMINVITATION
  
  # @@protoc_insertion_point(class_scope:TeamInvitation)

class TeamJoiningApplicationMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMJOININGAPPLICATIONMESSAGE
  
  # @@protoc_insertion_point(class_scope:TeamJoiningApplicationMessage)

class TeamMemberStatusUpdated(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMMEMBERSTATUSUPDATED
  
  # @@protoc_insertion_point(class_scope:TeamMemberStatusUpdated)

class TeamJoiningApplicationAccepted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMJOININGAPPLICATIONACCEPTED
  
  # @@protoc_insertion_point(class_scope:TeamJoiningApplicationAccepted)

class TeamJoiningApplicationDeclined(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMJOININGAPPLICATIONDECLINED
  
  # @@protoc_insertion_point(class_scope:TeamJoiningApplicationDeclined)

class TeamDisbanded(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMDISBANDED
  
  # @@protoc_insertion_point(class_scope:TeamDisbanded)

class TeamLeaderChanged(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMLEADERCHANGED
  
  # @@protoc_insertion_point(class_scope:TeamLeaderChanged)

# @@protoc_insertion_point(module_scope)
