# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_clan.proto',
  package='',
  serialized_pb='\n\x0emsg_clan.proto\"\x19\n\x17\x41lertJoiningClanMessageB\r\n\tproto.msgH\x02')




_ALERTJOININGCLANMESSAGE = descriptor.Descriptor(
  name='AlertJoiningClanMessage',
  full_name='AlertJoiningClanMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=43,
)



class AlertJoiningClanMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALERTJOININGCLANMESSAGE
  
  # @@protoc_insertion_point(class_scope:AlertJoiningClanMessage)

# @@protoc_insertion_point(module_scope)
