# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_user.proto',
  package='',
  serialized_pb='\n\x0emsg_user.proto\x1a\x0eres_user.proto\"5\n\x13\x42\x65\x63\x61meFriendMessage\x12\x1e\n\ntargetUser\x18\x01 \x01(\x0b\x32\n.UserModel\"<\n\x1a\x46riendStatusChangedMessage\x12\x0e\n\x06userID\x18\x01 \x01(\r\x12\x0e\n\x06status\x18\x02 \x01(\t\"D\n\x18\x46riendDataChangedMessage\x12\x0e\n\x06userID\x18\x01 \x01(\r\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.UserModel\"S\n\x11MakeFriendMessage\x12\x1c\n\x08\x66romUser\x18\x01 \x01(\x0b\x32\n.UserModel\x12\x10\n\x08toUserID\x18\x02 \x01(\r\x12\x0e\n\x06reason\x18\x03 \x01(\t\"G\n\x0eWhisperMessage\x12\x12\n\nfromUserID\x18\x01 \x01(\r\x12\x10\n\x08toUserID\x18\x02 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x1b\n\x19\x41lertValidateEmailMessage\"3\n\x0cUserAccepted\x12\x15\n\ransweredMsgID\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\"3\n\x0cUserDeclined\x12\x15\n\ransweredMsgID\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\"D\n\x12MakeFriendAccepted\x12\x12\n\nfromUserID\x18\x01 \x01(\r\x12\x1a\n\x06toUser\x18\x02 \x01(\x0b\x32\n.UserModel\"D\n\x12MakeFriendDeclined\x12\x12\n\nfromUserID\x18\x01 \x01(\r\x12\x1a\n\x06toUser\x18\x02 \x01(\x0b\x32\n.UserModel\",\n\x10UserStatusUpdate\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.UserModelB\r\n\tproto.msgH\x02')




_BECAMEFRIENDMESSAGE = descriptor.Descriptor(
  name='BecameFriendMessage',
  full_name='BecameFriendMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='targetUser', full_name='BecameFriendMessage.targetUser', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=87,
)


_FRIENDSTATUSCHANGEDMESSAGE = descriptor.Descriptor(
  name='FriendStatusChangedMessage',
  full_name='FriendStatusChangedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userID', full_name='FriendStatusChangedMessage.userID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='FriendStatusChangedMessage.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=89,
  serialized_end=149,
)


_FRIENDDATACHANGEDMESSAGE = descriptor.Descriptor(
  name='FriendDataChangedMessage',
  full_name='FriendDataChangedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userID', full_name='FriendDataChangedMessage.userID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='FriendDataChangedMessage.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=151,
  serialized_end=219,
)


_MAKEFRIENDMESSAGE = descriptor.Descriptor(
  name='MakeFriendMessage',
  full_name='MakeFriendMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fromUser', full_name='MakeFriendMessage.fromUser', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='toUserID', full_name='MakeFriendMessage.toUserID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reason', full_name='MakeFriendMessage.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=221,
  serialized_end=304,
)


_WHISPERMESSAGE = descriptor.Descriptor(
  name='WhisperMessage',
  full_name='WhisperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fromUserID', full_name='WhisperMessage.fromUserID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='toUserID', full_name='WhisperMessage.toUserID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='WhisperMessage.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=306,
  serialized_end=377,
)


_ALERTVALIDATEEMAILMESSAGE = descriptor.Descriptor(
  name='AlertValidateEmailMessage',
  full_name='AlertValidateEmailMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=379,
  serialized_end=406,
)


_USERACCEPTED = descriptor.Descriptor(
  name='UserAccepted',
  full_name='UserAccepted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='answeredMsgID', full_name='UserAccepted.answeredMsgID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='UserAccepted.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=408,
  serialized_end=459,
)


_USERDECLINED = descriptor.Descriptor(
  name='UserDeclined',
  full_name='UserDeclined',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='answeredMsgID', full_name='UserDeclined.answeredMsgID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='UserDeclined.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=461,
  serialized_end=512,
)


_MAKEFRIENDACCEPTED = descriptor.Descriptor(
  name='MakeFriendAccepted',
  full_name='MakeFriendAccepted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fromUserID', full_name='MakeFriendAccepted.fromUserID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='toUser', full_name='MakeFriendAccepted.toUser', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=514,
  serialized_end=582,
)


_MAKEFRIENDDECLINED = descriptor.Descriptor(
  name='MakeFriendDeclined',
  full_name='MakeFriendDeclined',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fromUserID', full_name='MakeFriendDeclined.fromUserID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='toUser', full_name='MakeFriendDeclined.toUser', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=584,
  serialized_end=652,
)


_USERSTATUSUPDATE = descriptor.Descriptor(
  name='UserStatusUpdate',
  full_name='UserStatusUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='UserStatusUpdate.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=654,
  serialized_end=698,
)

import res_user_pb2

_BECAMEFRIENDMESSAGE.fields_by_name['targetUser'].message_type = res_user_pb2._USERMODEL
_FRIENDDATACHANGEDMESSAGE.fields_by_name['user'].message_type = res_user_pb2._USERMODEL
_MAKEFRIENDMESSAGE.fields_by_name['fromUser'].message_type = res_user_pb2._USERMODEL
_MAKEFRIENDACCEPTED.fields_by_name['toUser'].message_type = res_user_pb2._USERMODEL
_MAKEFRIENDDECLINED.fields_by_name['toUser'].message_type = res_user_pb2._USERMODEL
_USERSTATUSUPDATE.fields_by_name['user'].message_type = res_user_pb2._USERMODEL

class BecameFriendMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BECAMEFRIENDMESSAGE
  
  # @@protoc_insertion_point(class_scope:BecameFriendMessage)

class FriendStatusChangedMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRIENDSTATUSCHANGEDMESSAGE
  
  # @@protoc_insertion_point(class_scope:FriendStatusChangedMessage)

class FriendDataChangedMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRIENDDATACHANGEDMESSAGE
  
  # @@protoc_insertion_point(class_scope:FriendDataChangedMessage)

class MakeFriendMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAKEFRIENDMESSAGE
  
  # @@protoc_insertion_point(class_scope:MakeFriendMessage)

class WhisperMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WHISPERMESSAGE
  
  # @@protoc_insertion_point(class_scope:WhisperMessage)

class AlertValidateEmailMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALERTVALIDATEEMAILMESSAGE
  
  # @@protoc_insertion_point(class_scope:AlertValidateEmailMessage)

class UserAccepted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERACCEPTED
  
  # @@protoc_insertion_point(class_scope:UserAccepted)

class UserDeclined(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERDECLINED
  
  # @@protoc_insertion_point(class_scope:UserDeclined)

class MakeFriendAccepted(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAKEFRIENDACCEPTED
  
  # @@protoc_insertion_point(class_scope:MakeFriendAccepted)

class MakeFriendDeclined(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAKEFRIENDDECLINED
  
  # @@protoc_insertion_point(class_scope:MakeFriendDeclined)

class UserStatusUpdate(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERSTATUSUPDATE
  
  # @@protoc_insertion_point(class_scope:UserStatusUpdate)

# @@protoc_insertion_point(module_scope)
