# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='res_inet.proto',
  package='',
  serialized_pb='\n\x0eres_inet.proto\x1a\x0eres_user.proto\x1a\x12res_listbase.proto\x1a\x0eres_game.proto\"+\n\rInetTableList\x12\x1a\n\x06tables\x18\x01 \x03(\x0b\x32\n.InetTable\"]\n\tInetTable\x12\n\n\x02id\x18\x01 \x02(\r\x12\x11\n\tseatCount\x18\x02 \x02(\r\x12\x1d\n\x05seats\x18\x03 \x03(\x0b\x32\x0e.InetTableSlot\x12\x12\n\x04gmap\x18\x04 \x01(\x0b\x32\x04.Map\"g\n\rInetTableSlot\x12\x0e\n\x06\x64\x65skID\x18\x03 \x01(\r\x12\x0e\n\x06seatID\x18\x01 \x02(\r\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.UserModel\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0c\n\x04race\x18\x05 \x01(\r\"G\n\tInetStats\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.InetStatsItem\x12\x1b\n\x06params\x18\x02 \x01(\x0b\x32\x0b.ListParams\"\xb6\x01\n\rInetStatsItem\x12\n\n\x02id\x18\x0b \x02(\r\x12\x0c\n\x04name\x18\n \x01(\t\x12\x0c\n\x04rank\x18\x01 \x01(\r\x12\x0b\n\x03\x65xp\x18\x02 \x02(\r\x12\r\n\x05level\x18\x03 \x02(\x05\x12\x0b\n\x03\x63\x61\x62\x18\x04 \x02(\r\x12\n\n\x02R5\x18\x05 \x02(\t\x12\x0b\n\x03win\x18\x06 \x02(\r\x12\x0c\n\x04loss\x18\x07 \x02(\r\x12\r\n\x05total\x18\x08 \x02(\r\x12\x0c\n\x04rate\x18\t \x02(\x02\x12\x10\n\x08portrait\x18\x0c \x02(\tB\x12\n\x0eproto.responseH\x02')




_INETTABLELIST = descriptor.Descriptor(
  name='InetTableList',
  full_name='InetTableList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tables', full_name='InetTableList.tables', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=70,
  serialized_end=113,
)


_INETTABLE = descriptor.Descriptor(
  name='InetTable',
  full_name='InetTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='InetTable.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seatCount', full_name='InetTable.seatCount', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seats', full_name='InetTable.seats', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gmap', full_name='InetTable.gmap', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=115,
  serialized_end=208,
)


_INETTABLESLOT = descriptor.Descriptor(
  name='InetTableSlot',
  full_name='InetTableSlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='deskID', full_name='InetTableSlot.deskID', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seatID', full_name='InetTableSlot.seatID', index=1,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='InetTableSlot.user', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='InetTableSlot.status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='race', full_name='InetTableSlot.race', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=210,
  serialized_end=313,
)


_INETSTATS = descriptor.Descriptor(
  name='InetStats',
  full_name='InetStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='items', full_name='InetStats.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='params', full_name='InetStats.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=315,
  serialized_end=386,
)


_INETSTATSITEM = descriptor.Descriptor(
  name='InetStatsItem',
  full_name='InetStatsItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='InetStatsItem.id', index=0,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='InetStatsItem.name', index=1,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rank', full_name='InetStatsItem.rank', index=2,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exp', full_name='InetStatsItem.exp', index=3,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='level', full_name='InetStatsItem.level', index=4,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cab', full_name='InetStatsItem.cab', index=5,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='R5', full_name='InetStatsItem.R5', index=6,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='win', full_name='InetStatsItem.win', index=7,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='loss', full_name='InetStatsItem.loss', index=8,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='total', full_name='InetStatsItem.total', index=9,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rate', full_name='InetStatsItem.rate', index=10,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='portrait', full_name='InetStatsItem.portrait', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=389,
  serialized_end=571,
)

import res_user_pb2
import res_listbase_pb2
import res_game_pb2

_INETTABLELIST.fields_by_name['tables'].message_type = _INETTABLE
_INETTABLE.fields_by_name['seats'].message_type = _INETTABLESLOT
_INETTABLE.fields_by_name['gmap'].message_type = res_game_pb2._MAP
_INETTABLESLOT.fields_by_name['user'].message_type = res_user_pb2._USERMODEL
_INETSTATS.fields_by_name['items'].message_type = _INETSTATSITEM
_INETSTATS.fields_by_name['params'].message_type = res_listbase_pb2._LISTPARAMS

class InetTableList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INETTABLELIST
  
  # @@protoc_insertion_point(class_scope:InetTableList)

class InetTable(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INETTABLE
  
  # @@protoc_insertion_point(class_scope:InetTable)

class InetTableSlot(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INETTABLESLOT
  
  # @@protoc_insertion_point(class_scope:InetTableSlot)

class InetStats(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INETSTATS
  
  # @@protoc_insertion_point(class_scope:InetStats)

class InetStatsItem(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INETSTATSITEM
  
  # @@protoc_insertion_point(class_scope:InetStatsItem)

# @@protoc_insertion_point(module_scope)
