# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='res_gameres.proto',
  package='',
  serialized_pb='\n\x11res_gameres.proto\x1a\x14res_war3detail.proto\x1a\x0cres_sc.proto\"l\n\x0bGameMessage\x12\x0e\n\x06subMsg\x18\x01 \x01(\t\x12!\n\tstarcraft\x18\x02 \x03(\x0b\x32\x0e.StarCraftData\x12\x19\n\x04war3\x18\x03 \x03(\x0b\x32\x0b.War3Detail\x12\x0f\n\x07\x41renaID\x18\x04 \x01(\x05\x42\x12\n\x0eproto.responseH\x02')




_GAMEMESSAGE = descriptor.Descriptor(
  name='GameMessage',
  full_name='GameMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='subMsg', full_name='GameMessage.subMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='starcraft', full_name='GameMessage.starcraft', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='war3', full_name='GameMessage.war3', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ArenaID', full_name='GameMessage.ArenaID', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=165,
)

import res_war3detail_pb2
import res_sc_pb2

_GAMEMESSAGE.fields_by_name['starcraft'].message_type = res_sc_pb2._STARCRAFTDATA
_GAMEMESSAGE.fields_by_name['war3'].message_type = res_war3detail_pb2._WAR3DETAIL

class GameMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMEMESSAGE
  
  # @@protoc_insertion_point(class_scope:GameMessage)

# @@protoc_insertion_point(module_scope)
