# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='res_activity.proto',
  package='',
  serialized_pb='\n\x12res_activity.proto\x1a\x12res_listbase.proto\"P\n\x13\x41\x63tivityGetResponse\x12\n\n\x02id\x18\x04 \x01(\r\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04logo\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\r\"]\n\x14\x41\x63tivityListResponse\x12(\n\nactivities\x18\x01 \x03(\x0b\x32\x14.ActivityGetResponse\x12\x1b\n\x06params\x18\x02 \x01(\x0b\x32\x0b.ListParamsB\x12\n\x0eproto.responseH\x02')




_ACTIVITYGETRESPONSE = descriptor.Descriptor(
  name='ActivityGetResponse',
  full_name='ActivityGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='ActivityGetResponse.id', index=0,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='ActivityGetResponse.text', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='logo', full_name='ActivityGetResponse.logo', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='ActivityGetResponse.timestamp', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=122,
)


_ACTIVITYLISTRESPONSE = descriptor.Descriptor(
  name='ActivityListResponse',
  full_name='ActivityListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='activities', full_name='ActivityListResponse.activities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='params', full_name='ActivityListResponse.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=124,
  serialized_end=217,
)

import res_listbase_pb2

_ACTIVITYLISTRESPONSE.fields_by_name['activities'].message_type = _ACTIVITYGETRESPONSE
_ACTIVITYLISTRESPONSE.fields_by_name['params'].message_type = res_listbase_pb2._LISTPARAMS

class ActivityGetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIVITYGETRESPONSE
  
  # @@protoc_insertion_point(class_scope:ActivityGetResponse)

class ActivityListResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIVITYLISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:ActivityListResponse)

# @@protoc_insertion_point(module_scope)
