# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='res_listbase.proto',
  package='',
  serialized_pb='\n\x12res_listbase.proto\"]\n\nListParams\x12\x13\n\x0bisPaginated\x18\x02 \x02(\x08\x12\x0c\n\x04hits\x18\x03 \x01(\r\x12\x0c\n\x04page\x18\x04 \x01(\r\x12\x0f\n\x07perpage\x18\x05 \x01(\r\x12\r\n\x05pages\x18\x06 \x01(\rB\x12\n\x0eproto.responseH\x02')




_LISTPARAMS = descriptor.Descriptor(
  name='ListParams',
  full_name='ListParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='isPaginated', full_name='ListParams.isPaginated', index=0,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hits', full_name='ListParams.hits', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='page', full_name='ListParams.page', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='perpage', full_name='ListParams.perpage', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pages', full_name='ListParams.pages', index=4,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=115,
)



class ListParams(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LISTPARAMS
  
  # @@protoc_insertion_point(class_scope:ListParams)

# @@protoc_insertion_point(module_scope)
