# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='res_battle.proto',
  package='',
  serialized_pb='\n\x10res_battle.proto\x1a\x14res_war3detail.proto\x1a\nutil.proto\"\x81\x01\n\rBattleMessage\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\x19\n\x04war3\x18\x02 \x01(\x0b\x32\x0b.War3Detail\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\tstartTime\x18\x08 \x01(\r\x12\x11\n\teventName\x18\n \x01(\t\x12\x13\n\x0breplay_file\x18\x0b \x01(\t\"-\n\nBattleList\x12\x1f\n\x07\x62\x61ttles\x18\x01 \x03(\x0b\x32\x0e.BattleMessageB\r\n\tproto.resH\x02')




_BATTLEMESSAGE = descriptor.Descriptor(
  name='BattleMessage',
  full_name='BattleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uuid', full_name='BattleMessage.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='war3', full_name='BattleMessage.war3', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='BattleMessage.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startTime', full_name='BattleMessage.startTime', index=3,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eventName', full_name='BattleMessage.eventName', index=4,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='replay_file', full_name='BattleMessage.replay_file', index=5,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=184,
)


_BATTLELIST = descriptor.Descriptor(
  name='BattleList',
  full_name='BattleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='battles', full_name='BattleList.battles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=186,
  serialized_end=231,
)

import res_war3detail_pb2
import util_pb2

_BATTLEMESSAGE.fields_by_name['war3'].message_type = res_war3detail_pb2._WAR3DETAIL
_BATTLELIST.fields_by_name['battles'].message_type = _BATTLEMESSAGE

class BattleMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTLEMESSAGE
  
  # @@protoc_insertion_point(class_scope:BattleMessage)

class BattleList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTLELIST
  
  # @@protoc_insertion_point(class_scope:BattleList)

# @@protoc_insertion_point(module_scope)
