# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='res_party.proto',
  package='',
  serialized_pb='\n\x0fres_party.proto\x1a\x0eres_user.proto\x1a\x12res_listbase.proto\"^\n\x10PartyGetResponse\x12\n\n\x02id\x18\x01 \x02(\r\x12\x19\n\x05users\x18\x02 \x03(\x0b\x32\n.UserModel\x12\x10\n\x08leaderID\x18\x03 \x01(\r\x12\x11\n\tuserCount\x18\x04 \x01(\r\"T\n\x11PartyListResponse\x12\"\n\x07parties\x18\x01 \x03(\x0b\x32\x11.PartyGetResponse\x12\x1b\n\x06params\x18\x02 \x01(\x0b\x32\x0b.ListParamsB\x12\n\x0eproto.responseH\x02')




_PARTYGETRESPONSE = descriptor.Descriptor(
  name='PartyGetResponse',
  full_name='PartyGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='PartyGetResponse.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='users', full_name='PartyGetResponse.users', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='leaderID', full_name='PartyGetResponse.leaderID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userCount', full_name='PartyGetResponse.userCount', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=149,
)


_PARTYLISTRESPONSE = descriptor.Descriptor(
  name='PartyListResponse',
  full_name='PartyListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='parties', full_name='PartyListResponse.parties', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='params', full_name='PartyListResponse.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=151,
  serialized_end=235,
)

import res_user_pb2
import res_listbase_pb2

_PARTYGETRESPONSE.fields_by_name['users'].message_type = res_user_pb2._USERMODEL
_PARTYLISTRESPONSE.fields_by_name['parties'].message_type = _PARTYGETRESPONSE
_PARTYLISTRESPONSE.fields_by_name['params'].message_type = res_listbase_pb2._LISTPARAMS

class PartyGetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTYGETRESPONSE
  
  # @@protoc_insertion_point(class_scope:PartyGetResponse)

class PartyListResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTYLISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:PartyListResponse)

# @@protoc_insertion_point(module_scope)
