# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='res_battle.proto',
  package='',
  serialized_pb='\n\x10res_battle.proto\x1a\x0eres_user.proto\x1a\x0eres_game.proto\x1a\nutil.proto\"\x9b\x02\n\x06\x42\x61ttle\x12\n\n\x02id\x18\x01 \x01(\r\x12!\n\x0blogicalGame\x18\x02 \x01(\x0b\x32\x0c.LogicalGame\x12#\n\x0cphysicalGame\x18\x03 \x01(\x0b\x32\r.PhysicalGame\x12\x11\n\x03map\x18\x04 \x01(\x0b\x32\x04.Map\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x1e\n\x07players\x18\x06 \x03(\x0b\x32\r.BattlePlayer\x12#\n\nattributes\x18\x07 \x01(\x0b\x32\x0f.StringDictItem\x12\x11\n\tstartTime\x18\x08 \x01(\r\x12\x0f\n\x07\x65ndTime\x18\t \x01(\r\x12\x0f\n\x07mappath\x18\x10 \x01(\t\x12\x10\n\x08gamepath\x18\x11 \x01(\t\x12\x0e\n\x06hostID\x18\x12 \x01(\r\"p\n\x0c\x42\x61ttlePlayer\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.UserModel\x12\x10\n\x08position\x18\x02 \x01(\r\x12\x0f\n\x07\x66orceid\x18\x03 \x01(\r\x12#\n\nattributes\x18\x04 \x03(\x0b\x32\x0f.StringDictItemB\r\n\tproto.resH\x02')




_BATTLE = descriptor.Descriptor(
  name='Battle',
  full_name='Battle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Battle.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='logicalGame', full_name='Battle.logicalGame', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='physicalGame', full_name='Battle.physicalGame', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='map', full_name='Battle.map', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='Battle.status', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='players', full_name='Battle.players', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attributes', full_name='Battle.attributes', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startTime', full_name='Battle.startTime', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endTime', full_name='Battle.endTime', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mappath', full_name='Battle.mappath', index=9,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gamepath', full_name='Battle.gamepath', index=10,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hostID', full_name='Battle.hostID', index=11,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=348,
)


_BATTLEPLAYER = descriptor.Descriptor(
  name='BattlePlayer',
  full_name='BattlePlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='BattlePlayer.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position', full_name='BattlePlayer.position', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='forceid', full_name='BattlePlayer.forceid', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attributes', full_name='BattlePlayer.attributes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=350,
  serialized_end=462,
)

import res_user_pb2
import res_game_pb2
import util_pb2

_BATTLE.fields_by_name['logicalGame'].message_type = res_game_pb2._LOGICALGAME
_BATTLE.fields_by_name['physicalGame'].message_type = res_game_pb2._PHYSICALGAME
_BATTLE.fields_by_name['map'].message_type = res_game_pb2._MAP
_BATTLE.fields_by_name['players'].message_type = _BATTLEPLAYER
_BATTLE.fields_by_name['attributes'].message_type = util_pb2._STRINGDICTITEM
_BATTLEPLAYER.fields_by_name['user'].message_type = res_user_pb2._USERMODEL
_BATTLEPLAYER.fields_by_name['attributes'].message_type = util_pb2._STRINGDICTITEM

class Battle(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTLE
  
  # @@protoc_insertion_point(class_scope:Battle)

class BattlePlayer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTLEPLAYER
  
  # @@protoc_insertion_point(class_scope:BattlePlayer)

# @@protoc_insertion_point(module_scope)
