# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='test_performence.proto',
  package='',
  serialized_pb='\n\x16test_performence.proto\"\x14\n\x04Msg1\x12\x0c\n\x04text\x18\x01 \x01(\r\"\x14\n\x04Msg2\x12\x0c\n\x04text\x18\x01 \x01(\r\"\x14\n\x04Msg3\x12\x0c\n\x04text\x18\x01 \x01(\r\"\x14\n\x04Msg4\x12\x0c\n\x04text\x18\x01 \x01(\r\"\x14\n\x04Msg5\x12\x0c\n\x04text\x18\x01 \x01(\r\"\x14\n\x04Msg6\x12\x0c\n\x04text\x18\x01 \x01(\r\"\x14\n\x04Msg7\x12\x0c\n\x04text\x18\x01 \x01(\r\"\x14\n\x04Msg8\x12\x0c\n\x04text\x18\x01 \x01(\r\"\x14\n\x04Msg9\x12\x0c\n\x04text\x18\x01 \x01(\r\"\x14\n\x04Msg0\x12\x0c\n\x04text\x18\x01 \x01(\r\"\xed\x01\n\x19OptionalCompositedMessage\x12\x13\n\x04msg1\x18\x01 \x01(\x0b\x32\x05.Msg1\x12\x13\n\x04msg2\x18\x02 \x01(\x0b\x32\x05.Msg2\x12\x13\n\x04msg3\x18\x03 \x01(\x0b\x32\x05.Msg3\x12\x13\n\x04msg4\x18\x04 \x01(\x0b\x32\x05.Msg4\x12\x13\n\x04msg5\x18\x05 \x01(\x0b\x32\x05.Msg5\x12\x13\n\x04msg6\x18\x06 \x01(\x0b\x32\x05.Msg6\x12\x13\n\x04msg7\x18\x07 \x01(\x0b\x32\x05.Msg7\x12\x13\n\x04msg8\x18\x08 \x01(\x0b\x32\x05.Msg8\x12\x13\n\x04msg9\x18\t \x01(\x0b\x32\x05.Msg9\x12\x13\n\x04msg0\x18\n \x01(\x0b\x32\x05.Msg0\".\n\x17SingleCompositedMessage\x12\x13\n\x04msg0\x18\n \x01(\x0b\x32\x05.Msg0\"%\n\x19\x45xtentedCompositedMessage*\x08\x08\x01\x10\x80\x80\x80\x80\x02\"/\n\x06Ocuped\x12%\n\x01m\x18\x01 \x02(\x0b\x32\x1a.ExtentedCompositedMessage:(\n\x04msg0\x12\x1a.ExtentedCompositedMessage\x18\n \x01(\r:(\n\x04msg1\x12\x1a.ExtentedCompositedMessage\x18\x01 \x01(\r:(\n\x04msg2\x12\x1a.ExtentedCompositedMessage\x18\x02 \x01(\r:(\n\x04msg3\x12\x1a.ExtentedCompositedMessage\x18\x03 \x01(\r:(\n\x04msg4\x12\x1a.ExtentedCompositedMessage\x18\x04 \x01(\r:(\n\x04msg5\x12\x1a.ExtentedCompositedMessage\x18\x05 \x01(\r:(\n\x04msg6\x12\x1a.ExtentedCompositedMessage\x18\x06 \x01(\r:(\n\x04msg7\x12\x1a.ExtentedCompositedMessage\x18\x07 \x01(\r:(\n\x04msg8\x12\x1a.ExtentedCompositedMessage\x18\x08 \x01(\r:(\n\x04msg9\x12\x1a.ExtentedCompositedMessage\x18\t \x01(\r')


MSG0_FIELD_NUMBER = 10
msg0 = descriptor.FieldDescriptor(
  name='msg0', full_name='msg0', index=0,
  number=10, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MSG1_FIELD_NUMBER = 1
msg1 = descriptor.FieldDescriptor(
  name='msg1', full_name='msg1', index=1,
  number=1, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MSG2_FIELD_NUMBER = 2
msg2 = descriptor.FieldDescriptor(
  name='msg2', full_name='msg2', index=2,
  number=2, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MSG3_FIELD_NUMBER = 3
msg3 = descriptor.FieldDescriptor(
  name='msg3', full_name='msg3', index=3,
  number=3, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MSG4_FIELD_NUMBER = 4
msg4 = descriptor.FieldDescriptor(
  name='msg4', full_name='msg4', index=4,
  number=4, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MSG5_FIELD_NUMBER = 5
msg5 = descriptor.FieldDescriptor(
  name='msg5', full_name='msg5', index=5,
  number=5, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MSG6_FIELD_NUMBER = 6
msg6 = descriptor.FieldDescriptor(
  name='msg6', full_name='msg6', index=6,
  number=6, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MSG7_FIELD_NUMBER = 7
msg7 = descriptor.FieldDescriptor(
  name='msg7', full_name='msg7', index=7,
  number=7, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MSG8_FIELD_NUMBER = 8
msg8 = descriptor.FieldDescriptor(
  name='msg8', full_name='msg8', index=8,
  number=8, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MSG9_FIELD_NUMBER = 9
msg9 = descriptor.FieldDescriptor(
  name='msg9', full_name='msg9', index=9,
  number=9, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_MSG1 = descriptor.Descriptor(
  name='Msg1',
  full_name='Msg1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg1.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=46,
)


_MSG2 = descriptor.Descriptor(
  name='Msg2',
  full_name='Msg2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg2.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=68,
)


_MSG3 = descriptor.Descriptor(
  name='Msg3',
  full_name='Msg3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg3.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=70,
  serialized_end=90,
)


_MSG4 = descriptor.Descriptor(
  name='Msg4',
  full_name='Msg4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg4.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=92,
  serialized_end=112,
)


_MSG5 = descriptor.Descriptor(
  name='Msg5',
  full_name='Msg5',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg5.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=114,
  serialized_end=134,
)


_MSG6 = descriptor.Descriptor(
  name='Msg6',
  full_name='Msg6',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg6.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=136,
  serialized_end=156,
)


_MSG7 = descriptor.Descriptor(
  name='Msg7',
  full_name='Msg7',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg7.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=158,
  serialized_end=178,
)


_MSG8 = descriptor.Descriptor(
  name='Msg8',
  full_name='Msg8',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg8.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=180,
  serialized_end=200,
)


_MSG9 = descriptor.Descriptor(
  name='Msg9',
  full_name='Msg9',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg9.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=202,
  serialized_end=222,
)


_MSG0 = descriptor.Descriptor(
  name='Msg0',
  full_name='Msg0',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='text', full_name='Msg0.text', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=224,
  serialized_end=244,
)


_OPTIONALCOMPOSITEDMESSAGE = descriptor.Descriptor(
  name='OptionalCompositedMessage',
  full_name='OptionalCompositedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='msg1', full_name='OptionalCompositedMessage.msg1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg2', full_name='OptionalCompositedMessage.msg2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg3', full_name='OptionalCompositedMessage.msg3', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg4', full_name='OptionalCompositedMessage.msg4', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg5', full_name='OptionalCompositedMessage.msg5', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg6', full_name='OptionalCompositedMessage.msg6', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg7', full_name='OptionalCompositedMessage.msg7', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg8', full_name='OptionalCompositedMessage.msg8', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg9', full_name='OptionalCompositedMessage.msg9', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg0', full_name='OptionalCompositedMessage.msg0', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=247,
  serialized_end=484,
)


_SINGLECOMPOSITEDMESSAGE = descriptor.Descriptor(
  name='SingleCompositedMessage',
  full_name='SingleCompositedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='msg0', full_name='SingleCompositedMessage.msg0', index=0,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=486,
  serialized_end=532,
)


_EXTENTEDCOMPOSITEDMESSAGE = descriptor.Descriptor(
  name='ExtentedCompositedMessage',
  full_name='ExtentedCompositedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(1, 536870912), ],
  serialized_start=534,
  serialized_end=571,
)


_OCUPED = descriptor.Descriptor(
  name='Ocuped',
  full_name='Ocuped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='m', full_name='Ocuped.m', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=573,
  serialized_end=620,
)


_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg1'].message_type = _MSG1
_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg2'].message_type = _MSG2
_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg3'].message_type = _MSG3
_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg4'].message_type = _MSG4
_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg5'].message_type = _MSG5
_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg6'].message_type = _MSG6
_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg7'].message_type = _MSG7
_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg8'].message_type = _MSG8
_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg9'].message_type = _MSG9
_OPTIONALCOMPOSITEDMESSAGE.fields_by_name['msg0'].message_type = _MSG0
_SINGLECOMPOSITEDMESSAGE.fields_by_name['msg0'].message_type = _MSG0
_OCUPED.fields_by_name['m'].message_type = _EXTENTEDCOMPOSITEDMESSAGE

class Msg1(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG1
  
  # @@protoc_insertion_point(class_scope:Msg1)

class Msg2(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG2
  
  # @@protoc_insertion_point(class_scope:Msg2)

class Msg3(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG3
  
  # @@protoc_insertion_point(class_scope:Msg3)

class Msg4(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG4
  
  # @@protoc_insertion_point(class_scope:Msg4)

class Msg5(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG5
  
  # @@protoc_insertion_point(class_scope:Msg5)

class Msg6(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG6
  
  # @@protoc_insertion_point(class_scope:Msg6)

class Msg7(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG7
  
  # @@protoc_insertion_point(class_scope:Msg7)

class Msg8(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG8
  
  # @@protoc_insertion_point(class_scope:Msg8)

class Msg9(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG9
  
  # @@protoc_insertion_point(class_scope:Msg9)

class Msg0(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG0
  
  # @@protoc_insertion_point(class_scope:Msg0)

class OptionalCompositedMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OPTIONALCOMPOSITEDMESSAGE
  
  # @@protoc_insertion_point(class_scope:OptionalCompositedMessage)

class SingleCompositedMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SINGLECOMPOSITEDMESSAGE
  
  # @@protoc_insertion_point(class_scope:SingleCompositedMessage)

class ExtentedCompositedMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTENTEDCOMPOSITEDMESSAGE
  
  # @@protoc_insertion_point(class_scope:ExtentedCompositedMessage)

class Ocuped(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OCUPED
  
  # @@protoc_insertion_point(class_scope:Ocuped)

ExtentedCompositedMessage.RegisterExtension(msg0)
ExtentedCompositedMessage.RegisterExtension(msg1)
ExtentedCompositedMessage.RegisterExtension(msg2)
ExtentedCompositedMessage.RegisterExtension(msg3)
ExtentedCompositedMessage.RegisterExtension(msg4)
ExtentedCompositedMessage.RegisterExtension(msg5)
ExtentedCompositedMessage.RegisterExtension(msg6)
ExtentedCompositedMessage.RegisterExtension(msg7)
ExtentedCompositedMessage.RegisterExtension(msg8)
ExtentedCompositedMessage.RegisterExtension(msg9)
# @@protoc_insertion_point(module_scope)
